### ISSUE TITLE
Pre-trained model unavailable	

### ISSUE THREAD

**Issue by CaptainPrice12** [clovaai/voxceleb_trainer#102]
Hi Joon Son, thank you for the update! 

But it seems some pre-trained models you provided are still unavailable. Links provided can be opened but models can't be downloaded. Would you mind check them when you are available? 

Some links having issues are shown as below:

ResNetSE34V2: https://www.robots.ox.ac.uk/~joon/data/baseline_v2_smproto.model

ResNetSE34V2: https://www.robots.ox.ac.uk/~joon/data/baseline_v2_ap.model

ResNetSE34L: https://www.robots.ox.ac.uk/~joon/data/baseline_lite_ap.model

Thank you so much!

**Comment by joonson** [comment]
It works fine for me. Can you try downloading using a different network / device?

**Comment by CaptainPrice12** [comment]
Thank you! It works if using Safari browser but doesn't work for Chrome even I use another device. I am not sure if anything wrong with Chrome......
