### ISSUE TITLE
Issues when trying different loss functions

### ISSUE THREAD

**Issue by SaniyaAbushakimova** [clovaai/voxceleb_trainer#109]
Hello!

## Issue 1: Softmax 
The first time when I tried to run the model with Softmax loss, I got the following error message:

```
File "softmax.py", line 24, in forward
    nloss   = self.criterion(x,label)
ValueError: Expected target size (100, 100), got torch.Size([100])
```

In the code the problem appeared to be in the areas inside a red box:
![softmax_1](https://user-images.githubusercontent.com/81459892/120880408-28a83c80-c5ec-11eb-80f7-4cf35a7a6416.png)

As it can be noticed from the comments in the above screenshot, **x** originally is of size (100, 10, 512), after going through an FC layer its size changes to (100, 10, 100), and then it is passed straight to **torch.nn.CrossEntropyLoss()** function. However, according to the [official PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html), this function requires the **x** to be of size (100, 100).

I have come up with a possible solution and was wondering whether the solution is reasonable and does not have any side effects on the model performance. The solution was to introduce additional transformations that will reduce (100, 10, 100) to (100, 100). It was done with the help of torch.mean(x, dim = 1, keepdim=False). As far as I know, such a method is legal in neural networks, more about the method can be found [here](https://pytorch.org/docs/stable/generated/torch.mean.html).

So, the adjusted code looks like this:
![softmax_2](https://user-images.githubusercontent.com/81459892/120880435-5db48f00-c5ec-11eb-9d8e-92733464e700.png)

In this way, the model with Softmax loss now runs and works perfectly fine. What do you think about this solution?

____________________________________________________________________________________
## Issue 2: Amsoftmax, AAmsoftmax
The same issue as with Softmax loss was also detected while using Amsoftmax and AAmsoftmax losses. These errors were resolved in the same manner. Below are the adjusted codes:
a) Amsoftmax
![amsoftmax](https://user-images.githubusercontent.com/81459892/120880445-7329b900-c5ec-11eb-811c-94a98c81b107.png)

b) AAmsoftmax
![aamsoftmax](https://user-images.githubusercontent.com/81459892/120880449-758c1300-c5ec-11eb-83df-fe022f8e2773.png)

____________________________________________________________________________________
## Issue 3: Triplet
The second issue that I encountered was involving the Triplet Loss. There were two main errors with that:

### Error 1: 

```
File "/home/sania_abushakimova/sf_pv/loss/triplet.py", line 26, in forward
    assert x.size()[1] == 2 
AssertionError
```

From the above message, it seems that in the code the error comes from the part highlighted in a red box.
![triplet_2](https://user-images.githubusercontent.com/81459892/120880464-8d639700-c5ec-11eb-99e4-3a5572100d5f.png)

After analyzing other metric-based losses, I came to a conclusion that **==** sign must be replaced to **>=**. Please correct me if my assumption was incorrect. (The error was resolved though)

Here are the screenshots from other losses that contain the same assert statement.
a) Proto
![proto](https://user-images.githubusercontent.com/81459892/120880479-a10efd80-c5ec-11eb-8d43-f5da7a2e5a6b.png)
b) AngleProto
![angleproto](https://user-images.githubusercontent.com/81459892/120880481-a3715780-c5ec-11eb-94a6-26af1c031e22.png)
c) Ge2e
![ge2e](https://user-images.githubusercontent.com/81459892/120880483-a79d7500-c5ec-11eb-95ef-677058859c76.png)

### Error 2: 
```
File "SpeakerNet.py", line 112, in train_network
    top1    += prec1.detach().cpu().item();
AttributeError: 'numpy.float64' object has no attribute 'detach'
```

This problem was caused due to **prec1** for some reason being a numpy array instead of a tensor. 
Below is one piece from SpeakerNet.py:
![speakernet1](https://user-images.githubusercontent.com/81459892/120880501-cd2a7e80-c5ec-11eb-9fc4-02cf25a2a722.png)

In order to solve this problem, I manually converted **prec1** to numpy array with the help of **torch.tensor(prec1)**. It eventually did solve the problem, but I was wondering whether it was a legal solution.
![speakernet2](https://user-images.githubusercontent.com/81459892/120880504-d3205f80-c5ec-11eb-88b2-7a6d48f09065.png)
____________________________________________________________________________________

Looking forward to your kind response, it will help me a lot with my research project!

**Comment by SaniyaAbushakimova** [comment]
Resolved

**Comment by yfchen97** [comment]
Excuse me, what is the result of using angleproto loss function? I got eer=2.6 minDCF=0.2. Is this normal? Does it belong to self-supervised learning method or supervised learning method?

**Comment by zabir-nabil** [comment]
Hi, @SaniyaAbushakimova did you find any discrepancy in results with this `mean` approach to avoid the assertion error?
