### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by CaptainPrice12** [clovaai/voxceleb_trainer#111]
Hi, thanks for this great work. I met a problem when I used the dataprep.py to download the Voxceleb data. When I run this python file, it got error as below:

**_HTTP request sent, awaiting response... 301 Moved Permanently_** and 
**_HTTP request sent, awaiting response... 404 Not Found_**
**_ERROR 404: Not Found_**

I am not sure if there is an issues with the data server. Could you please help me with it? Thank you!

**Comment by ukemamaster** [comment]
Use https://thor.robots.ox.ac.uk/ instead of http://www.robots.ox.ac.uk/ in all the lines in lists/fileparts.txt

**Comment by CaptainPrice12** [comment]
@ukemamaster Thanks for the help, it works!
