### ISSUE TITLE
Fast ResNet-34 specifications

### ISSUE THREAD

**Issue by hyperia-steven** [clovaai/voxceleb_trainer#12]
In the paper, you mention that "Due to space constraints, the exact specification [for Fast ResNet-34] can be found in the accompanying code." I can't find this specification in the repo. Can you point me to the right place?

**Comment by joonson** [comment]
The `ResNetSE34L` in the code refers to the Fast ResNet.

**Comment by hyperia-steven** [comment]
Thanks!
