### ISSUE TITLE
how to regist the person voice and predict it by new wav file

### ISSUE THREAD

**Issue by daizzhisheng** [clovaai/voxceleb_trainer#120]
with your code,i don't know how to regist the person's voice and predict it by new wav file.

**Comment by dimuthuanuraj** [comment]
@joonson Can you give an idea about this? How we can enroll a new speaker and test new single audio segments with your code?

**Comment by lengjiayi** [comment]
After training the SV network, it can generate speaker embeddings for new speakers as well. You can choose some utterances, save theirs embedding (enrollment), and then compare the cosine similarity of an unregistered voice and the saved embeddings. If the similarity is greater than the threshold, then they will be considered as the same person.

**Comment by SPDAnuraj** [comment]
@lengjiayi , I am kind of struggling on the save the embedding, Could you please explain how to do it in the code?
Really appreciate your support on this.

**Comment by dimuthuanuraj** [comment]
@lengjiayi  , I am kind of struggling on the save the embedding, Could you please explain how to do it in the code?
Really appreciate your support on this.

**Comment by Jungjee** [comment]
Hi @dimuthuanuraj . 
I recommend you to check out this: https://github.com/Jungjee/RawNet/blob/master/python/RawNet3/infererence.py. 
Especially `args.inference_utterance` part. 
Thank you.
