### ISSUE TITLE
Difference between speakerNet and speakerNet of NIVIDIA?

### ISSUE THREAD

**Issue by ali2iptoki** [clovaai/voxceleb_trainer#121]
What is the difference between your model and speakerNet proposed in this paper SPEAKERNET: 1D DEPTH-WISE SEPARABLE CONVOLUTIONAL NETWORK FOR TEXT-INDEPENDENT SPEAKER RECOGNITION AND VERIFICATION

Both you use the same name?

**Comment by ZhaZhaFon** [comment]
> What is the difference between your model and speakerNet proposed in this paper SPEAKERNET: 1D DEPTH-WISE SEPARABLE CONVOLUTIONAL NETWORK FOR TEXT-INDEPENDENT SPEAKER RECOGNITION AND VERIFICATION
> 
> Both you use the same name?

I think they just simply name the model class as 'SpeakerNet'.

**Comment by Jungjee** [comment]
The two models are different.
