### ISSUE TITLE
Train list & Evaluation list

### ISSUE THREAD

**Issue by dimuthuanuraj** [clovaai/voxceleb_trainer#122]
Anyone can help with the train list and evaluation list? 

From where I can find these both lists?
@joonson @dvisockas

**Comment by dvisockas** [comment]
They are daraset dependent. If you'll look into the Data section of the readme - you'll find links to get the voxceleb datasets and both links should be there

**Comment by dimuthuanuraj** [comment]
Thank you @dvisockas. Sorry, previously I did not notice that.
