### ISSUE TITLE
Lossfunction issue

### ISSUE THREAD

**Issue by makimon123** [clovaai/voxceleb_trainer#123]
when i tyoe the command“python ./trainSpeakerNet.py --model ResNetSE34V2 --log_input True --encoder_type SAP --trainfunc
 angleproto --save_path exps/exp1 --nClasses 5994 --batch_size 2 --margin 0.3”, I'll get the result below,
"IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)“  
but "--trainfunc amsoftmax" not

**Comment by makimon123** [comment]
error "nloss   = self.criterion(cos_sim_matrix, label) "

**Comment by Jungjee** [comment]
You have to set `nPerSpeaker` to 2 or a higher value to use `angleproto` as it is a metric learning loss function.

**Comment by yfchen97** [comment]
Excuse me, what is the result of using this loss function? I got eer=2.6 minDCF=0.2. Is this normal? Does it belong to self-supervised learning method or supervised learning method?

**Comment by makimon123** [comment]
> 您必须设置为 2 或更高的值才能使用，因为它是指标学习损失函数。`nPerSpeaker``angleproto`

thanks a bunch.
