### ISSUE TITLE
How you generate speaker embedding?

### ISSUE THREAD

**Issue by dimuthuanuraj** [clovaai/voxceleb_trainer#132]
I am wondering about how you extract the speaker embedding for a new speaker after train the model. I am a new to this area. Really appreciated it if you could explain about that @dvisockas @joonson .

**Comment by TheHonestBob** [comment]
did you solve it?

**Comment by SPDAnuraj** [comment]
@TheHonestBob Sorry I didn't able to complete that. Do you have any idea about this?

**Comment by TheHonestBob** [comment]
> @TheHonestBob Sorry I didn't able to complete that. Do you have any idea about this?

i just run python ./trainSpeakerNet.py --eval --model ResNetSE34L --log_input True --trainfunc angleproto --save_path exps/test --eval_frames 400 --initial_model baseline_lite_ap.model in readme , I use np.save to save https://github.com/clovaai/voxceleb_trainer/blob/a0466aa285106c631a58c0ddb8ea27805e13ef7b/SpeakerNet.py#L181 , but i don't know wether right or not, before that I modify some code

**Comment by dimuthuanuraj** [comment]
@TheHonestBob Could you please specify the place you have use the np.save?

**Comment by Jungjee** [comment]
Hi, if you want to save the speaker embedding while executing `evaluateFromList`, you can add `numpy.save(SAVE_DIR, ref_feat.numpy())` between these two lines.
https://github.com/clovaai/voxceleb_trainer/blob/9481143015109554840dcdd4a9bbefce897114a2/SpeakerNet.py#L181-L182
