### ISSUE TITLE
Use as Speaker Encoder for 48kHz audio

### ISSUE THREAD

**Issue by astricks** [clovaai/voxceleb_trainer#138]
Hello,

I am interested in a 48kHz version of this model. The provided model works very well with 22kHz audio as a speaker encoder for voice cloning TTS models. I now want to try it with 48kHz audio.

I just wanted to check if there was a model already available that was trained on a 48kHz dataset. Appreciate your time and help.

Warm regards.

**Comment by astricks** [comment]
Never mind, I figured it out.

**Comment by predawnang** [comment]
Hi, do you mean pre-trained rawnet3 model works very well with 22kHz audio? I recently plan to use rawnet3 within my project, but i'm not sure if the pre-trained version of rawnet3 works fine with 22050 sample rate raw waveform.
