### ISSUE TITLE
torch version for using 'all_gather_object'

### ISSUE THREAD

**Issue by msh9184** [clovaai/voxceleb_trainer#139]
It seems that **all_gather_object** from torch.distributed is available since torch 1.7.0 version. (Not available with the minimum versions (1.6.x) of requirements.py)
Thanks for checking it out.

**Comment by lbjcom** [comment]
Thanks for the comment. Would you please make a PR for the [requirements.txt](https://github.com/clovaai/voxceleb_trainer/blob/master/requirements.txt)?

**Comment by msh9184** [comment]
@lbjcom @hsss Thank you so much for your reply :-)
I made a [PR](https://github.com/clovaai/voxceleb_trainer/pull/140).
(This difference of dependency seems to cause an error when evaluation during ddp training in torch 1.6.0 version.)
