### ISSUE TITLE
Regarding negative similarity score

### ISSUE THREAD

**Issue by 009deep** [clovaai/voxceleb_trainer#15]
When I use  angleproto loss to train model, I see cosine similarity values coming negative for some of pairs with label 0. I haven't some across such cases with  softmax  or amsoftmax  losses. Is there  any explanation  why that might be happening?

**Comment by joonson** [comment]
Cosine similarity can be in the range [-1,1]. Shouldn't a negative score for a negative pair be a good thing?

**Comment by 009deep** [comment]
Below is quote from voxSRC  report  for 2019.   And it is first time when I saw value  being below 0. 

> All scores were required to be in the close interval [0, 1], where a similarity score of 1 means the pair of segments correspond to the same speaker and 0 means the pair of segments correspond to different speakers

Do you think above condition should be modified so that values are between [-1, 1]  or if not what to do in cases where similarity is less than 0?
Also, interpretation wise what does it  mean by negative similarity here, and correct me if  I am wrong but below is how I interpreted cosine similarity:
1: 100% belong to same person
0: 100% belong to different person
-1: ?

**Comment by hwidong-na** [comment]
https://en.wikipedia.org/wiki/Cosine_similarity#Angular_distance_and_similarity

**Comment by hwidong-na** [comment]
I tried [angular distance](https://en.wikipedia.org/wiki/Cosine_similarity#Angular_distance_and_similarity) and get better result.

**Comment by B05901022** [comment]
Maybe the cosine similarity is in the range of [-1,1] because the network output isn't ended with a relu activation like common models?
