### ISSUE TITLE
Video Dataset of VoxCeleb2

### ISSUE THREAD

**Issue by testzer0** [clovaai/voxceleb_trainer#152]
Hi, 
The links listed in fileparts.txt seem to only be the audio files. What are the corresponding links for the video (+audio) dataset parts?

Thanks.

**Comment by Jungjee** [comment]
We have the video links for VoxCeleb2 in https://mm.kaist.ac.kr/datasets/voxceleb/#downloads .

**Comment by brianw0924** [comment]
> We have the video links for VoxCeleb2 in https://mm.kaist.ac.kr/datasets/voxceleb/#downloads .

Hi, I was downloading the dataset but the website is down... and I haven't finish yet
