### ISSUE TITLE
training RawNet3 with new dataset

### ISSUE THREAD

**Issue by angelabr** [clovaai/voxceleb_trainer#158]
Hi,

When training Rawnet3 with the default config I get this error:

/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

Changing nClasses to a bigger number solves the problem but it looks like the model doesn't learn as EER gets stuck at 0, could you point me in the right direction to solve this?

Thank you

Angela BR

**Comment by Jungjee** [comment]
Hi, I think the error might have occurred because you did not set `nClasses` correctly.
Can you confirm if your `nClasses` is bigger than the actual number of speakers?
