### ISSUE TITLE
Download Speed

### ISSUE THREAD

**Issue by simasima121** [clovaai/voxceleb_trainer#161]
Hi

I'm downloading the dataset but it is very slow (~200 kB/sec compared to 200Mbps internet). Does anyone know how to speed this up?

Thanks

**Comment by jmosinski** [comment]
You could use multiprocessing. Try to parallelise functions in the dataprep.py.

**Comment by simasima121** [comment]
Thanks for help

Ended up using a VPN to download from South Korea which sped it up considerably.
