### ISSUE TITLE
ValueError: Conversion failed

### ISSUE THREAD

**Issue by KajiMaCN** [clovaai/voxceleb_trainer#164]
The path is correct. Why doesn't it convert?

(voxceleb) mzh@3-112:/data/mzh/voxceleb_trainer$ python ./dataprep.py --save_path data --convert
Converting files from AAC to WAV
  0%|                                                                      | 0/1092009 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./dataprep.py", line 205, in <module>
    convert(args)
  File "./dataprep.py", line 146, in convert
    raise ValueError('Conversion failed %s.'%fname)
ValueError: Conversion failed data/voxceleb2/id00012/21Uxsk56VDQ/00001.m4a.

**Comment by vasken** [comment]
Check that you have ffmpeg installed

**Comment by vasken** [comment]
Make sure you have ffmpeg installed
