### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by yuelei0428** [clovaai/voxceleb_trainer#176]
How can I get the dataset?
The previous link for getting username and password doesn't work now: https://docs.google.com/forms/d/e/1FAIpQLSdQhpq2Be2CktaPhuadUMU7ZDJoQuRlFlzNO45xO-drWQ0AXA/viewform?fbzx=7440236747203254000

I would be greatly appreciated if anyone could help :)
I've been stuck here for like several hours...

**Comment by marcoyang1998** [comment]
Hi, any updates on this? I was also wondering how to get the username and password.

**Comment by Jiltseb** [comment]
Any updates please?

**Comment by marcoyang1998** [comment]
You can request the dataset via this webpage (https://mm.kaist.ac.kr/datasets/voxceleb). Then you will receive links for downloading the data.

**Comment by DiLiangWU** [comment]
@marcoyang1998  The link does not work.  I'd like to ask if you have any idea? I would be appreciated.

**Comment by marcoyang1998** [comment]
> @marcoyang1998 The link does not work. I'd like to ask if you have any idea? I would be appreciated.

I just checked and the link is working. You might need to use VPN to access it.

**Comment by new-a-class** [comment]
You can download the data from https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/voxceleb/sv-eres2net/local/download_data.sh

**Comment by joonson** [comment]
The dataset is available from `https://mm.kaist.ac.kr/datasets/voxceleb/`

The download tool in `dataprep.py` has not yet been updated to reflect this change.
