### ISSUE TITLE
Dataset cannot be downloaded

### ISSUE THREAD

**Issue by zoroglu** [clovaai/voxceleb_trainer#177]
I tried two URL for downloding but give Connection timeout

**First url**
`https://mm.kaist.ac.kr/datasets/voxceleb`

**Second url**
`http://cnode01.mm.kaist.ac.kr/voxceleb/`

Where can I find the current URL?

**Comment by DiLiangWU** [comment]
I have the same problem as you. Have you found the solution?

**Comment by new-a-class** [comment]
You can download the data from https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/voxceleb/sv-eres2net/local/download_data.sh

**Comment by joonson** [comment]
The dataset is available from `https://mm.kaist.ac.kr/datasets/voxceleb/`

The download tool in `dataprep.py` has not yet been updated to reflect this change.
