### ISSUE TITLE
No Video Version of VoxCeleb1

### ISSUE THREAD

**Issue by CloudWalkerW** [clovaai/voxceleb_trainer#178]
Hi, I would like to ask if there's a possibility to get the **video versions of Voxceleb1**.

Are they still providing **video version** of Vox1 datasets?

Cause recently when I applied, I only can get audio version of Vox1 and audio+video versions of Vox2.

Can someone tell me where to get video version Vox1 datas?

Thanksssss!

**Comment by new-a-class** [comment]
Excuse me, have you obtained video version Vox1 datasets? I'm in the same situation as you.

**Comment by wxhqw** [comment]
> Excuse me, have you obtained video version Vox1 datasets? I'm in the same situation as you.

I also meet the same problem, have you solved it, i also need the video of the vox1

**Comment by joonson** [comment]
Video version of VoxCeleb1 has not been released, and it does not exist due to the nature of the pipeline (it used very tight crops not covering the whole face). You will need to crop using the provided coordinates from videos.
