### ISSUE TITLE
How can I get the USERNAME and PASSWORD?

### ISSUE THREAD

**Issue by DiLiangWU** [clovaai/voxceleb_trainer#184]
The link requesting USERNAME and PASSWORD doesn't work.
https://mm.kaist.ac.kr/datasets/voxceleb

How can I get the USERNAME and PASSWORD now?
Anyone can help me ?
I would really appreciate it.

**Comment by zx1292982431** [comment]
I have the same trouble. Have you found some solution?

**Comment by zx1292982431** [comment]
I found the same data on Huggingface. [here is the url](https://huggingface.co/datasets/ProgramComputer/voxceleb). I hope that can help you.

**Comment by new-a-class** [comment]
Download the data from https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/voxceleb/sv-eres2net/local/download_data.sh.

**Comment by new-a-class** [comment]
> I found the same data on Huggingface. [here is the url](https://huggingface.co/datasets/ProgramComputer/voxceleb). I hope that can help you.

How can we get the vox1 mp4 dataset?

**Comment by zx1292982431** [comment]
> > I found the same data on Huggingface. [here is the url](https://huggingface.co/datasets/ProgramComputer/voxceleb). I hope that can help you.
> 
> How can we get the vox1 mp4 dataset?

It seems like vox1 mp4 dataset is not supported in [https://huggingface.co/datasets/ProgramComputer/voxceleb](here), I only used the vox2 dataset.

**Comment by new-a-class** [comment]
> > > I found the same data on Huggingface. [here is the url](https://huggingface.co/datasets/ProgramComputer/voxceleb). I hope that can help you.
> > 
> > 
> > How can we get the vox1 mp4 dataset?
> 
> It seems like vox1 mp4 dataset is not supported in [https://huggingface.co/datasets/ProgramComputer/voxceleb](here), I only used the vox2 dataset.

Thank you very much.

**Comment by joonson** [comment]
The dataset is available from `https://mm.kaist.ac.kr/datasets/voxceleb/`

The download tool in `dataprep.py` has not yet been updated to reflect this change.

**Comment by Srinidhi2301** [comment]
hello, i still couldnt get the right procedure to download the voxceleb datasets. 
https://mm.kaist.ac.kr/datasets/voxceleb/index.html provides txt files and i couldnt find the audio files in it. 
also is there a procedure available to get our username and password

**Comment by mattpitkin** [comment]
> hello, i still couldnt get the right procedure to download the voxceleb datasets. https://mm.kaist.ac.kr/datasets/voxceleb/index.html provides txt files and i couldnt find the audio files in it. also is there a procedure available to get our username and password

@Srinidhi2301 what OS are you using? If you are using Linux/MacOS/WSL, then in a bash terminal you can run the following (or similar) to get the audio files (in a zipped archive) from the HuggingFace dataset:

```bash
URL=https://huggingface.co/datasets/ProgramComputer/voxceleb/resolve/main/vox2/
FILEBASE=vox2_dev_aac_parta
TESTFILE=vox2_test_aac.zip

for letter in a b c d e f g h; do
  FILE_URL=${URL}${FILEBASE}${letter}
  echo $FILE_URL
  wget $FILE_URL
done

# concatenate into 1 zip archive file
cat ${FILEBASE}* > vox2_acc.zip

# remove partial files
rm ${FILEBASE}*
```
