### ISSUE TITLE
Consistent metric for training and testing

### ISSUE THREAD

**Issue by hwidong-na** [clovaai/voxceleb_trainer#22]
Hi,

Thank you for great work.

I think the implementation has little flaw. Would it be more consistent to use same metric for training and test? Current implementation uses Euclidean distance whatever metric used in training.

https://github.com/clovaai/voxceleb_trainer/blob/de675ca3e3b27d21fb6f734558b47d6f4c81ac1c/SpeakerNet.py#L229

Best,
Hwidong

**Comment by joonson** [comment]
Hi,
Please see Q3 of Issue #4

**Comment by hwidong-na** [comment]
Thank you for pointing that.
