### ISSUE TITLE
Can't replicate the results

### ISSUE THREAD

**Issue by mussakhojayeva** [clovaai/voxceleb_trainer#24]
Hi! I trained the model using the parameters provided and got
IT 500, LR 0.000081, TEER/T1 66.35, TLOSS 1.446545, VEER 2.4920
with the best one on:
IT 480, LR 0.000090, TEER/T1 66.39, TLOSS 1.444428, VEER 2.4390

I used the following command:
python ./trainSpeakerNet.py --model ResNetSE34L --encoder SAP --trainfunc angleproto --optimizer adam --save_path data/exp1 --batch_size 800 --max_frames 200  

And using the provided meta_files for training (5994 speakers) and testing. 

Am I doing something wrong?

**Comment by 009deep** [comment]
What value of `nSpeakers` did you use?

**Comment by mussakhojayeva** [comment]
> What value of `nSpeakers` did you use?

default=6200

**Comment by joonson** [comment]
The results in the paper uses `max_frames=400` and the lowest accuracy of the 500 epochs. What accuracy get if you evaluate with this setting? You can use the model trained with a shorter `max_frames`.

**Comment by mussakhojayeva** [comment]
It worked! Thanks!

**Comment by mussakhojayeva** [comment]
> @mussakhojayeva Hi , may I know what max_frames do you use finally?

I used 200 for training and 400 for testing

**Comment by jlian2** [comment]
> > @mussakhojayeva Hi , may I know what max_frames do you use finally?
> 
> I used 200 for training and 400 for testing

Thanks!
