### ISSUE TITLE
Convergence 

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#29]
How come this model take so much epochs to train? It is a bit slow to converge

**Comment by joonson** [comment]
Using `ResNetSE34L`, it should take around 2 days for 500 epochs on Tesla V100 and around 3-4 days on GTX1080Ti.

**Comment by jlian2** [comment]
> Using `ResNetSE34L`, it should take around 2 days for 500 epochs on Tesla V100 and around 3-4 days on GTX1080Ti.

May I know how many Tesla V100s are you used? I am looking at AWS:
![image](https://user-images.githubusercontent.com/61141271/83840797-76ceeb00-a6cd-11ea-87cb-fcd029e80e6a.png)

**Comment by jlian2** [comment]
> Using `ResNetSE34L`, it should take around 2 days for 500 epochs on Tesla V100 and around 3-4 days on GTX1080Ti.

And what about the time on ResNetSE34?

**Comment by joonson** [comment]
One GPU. ResNetSE34 takes 5 days for 500 epochs.

**Comment by mmwebster** [comment]
Any chance you've plotted loss or EER scores against epochs during training? Or do you know roughly what EERs can be expected around 50, 100, or 200 epochs for ResNetSE34L? (working with limited compute resources at the moment)

**Comment by joonson** [comment]
See #1
