### ISSUE TITLE
Question about trade-off between batch size and max_frames

### ISSUE THREAD

**Issue by msh9184** [clovaai/voxceleb_trainer#3]
Hi. Thanks for the good resource!!

In your paper, the performance of the metric learning-based model is said to be affected by the batch size. I have two questions.

1. I'm wondering if max_frames and max_seg_per_spk also affect performance.
2. I would like to increase the batch size, but there is not enough GPU memory.
After seeing comments that multi GPU (Dataparallel) is not recommended, I am asking if reducing the max_frames to increase the batch size is the right way.

**Comment by joonson** [comment]
1. **max_frames** does affect performance. Between 100<**max_frames**<300, longer is better. I have not experimented with max_seg_per_spk.
2. No, for the reason stated above. I have heard that there are working third-party solutions for multi-GPU training, but this has not been verified.

**Comment by msh9184** [comment]
Thank you! :)

**Comment by joonson** [comment]
I have added a new model called `ResNet34L` which should perform similarly to `ResNet34` but use less than half the memory.

**Comment by llearner** [comment]
> I have added a new model called `ResNet34L` which should perform similarly to `ResNet34` but use less than half the memory.

Great! Did you evaluate the RestNet34L's performance?

**Comment by joonson** [comment]
Yes, around 2.3% EER using the angleproto loss. We will update the arXiv paper within a few days.

**Comment by msh9184** [comment]
Dear Mr. Chung,

 

Thank you very much..!

 

Sincerely,

Sunghwan Mun

**Comment by Shane-pe** [comment]
> 1. **max_frames** does affect performance. Between 100<**max_frames**<300, longer is better. I have not experimented with max_seg_per_spk.

Hi,  Mr. Chung, Thank you for all your effort and selfless support!
Did you mean you had tried different **max_frames** from 100 to 300 during **training**? And the result is the larger max_frames, the better performance?

**Comment by joonson** [comment]
Yes. Both during training and test.

**Comment by Shane-pe** [comment]
> Yes. Both during training and test.

@joonson 
Thanks.
BTW, you mentioned there was no data augmentation in your arXiv paper.

Have you tried data augmentation to train ResNet34 or ResNet34L later? And what's the result of performance?

If not, What is your idea if re-training the ResNet34L using augmented dataset(i. e., 5-fold augmented data from Kaldi)?  Will there be performance improvement?

**Comment by joonson** [comment]
We have not tried data augmentation. Augmentation usually improves the performance slightly, but we won't know until we try.

**Comment by Shane-pe** [comment]
> Yes. Both during training and test.

@joonson 
I just tried `--max_frames 300`, but got **negative result** compared to `--max_frames 200`.
No.|        model         |max_frames(train)|eval_frames(test)|  EER  
---|----------------------|-----------------|-----------------|-----
1  |model000000490.model  |200              |300              |2.2747
2  |model000000490.model  |200              |400              |*2.2057*
3  |model000000500.model  |200              |300              |2.3012
4  |model000000500.model  |200              |400              |2.2110
5  |baseline_lite_ap.model     |200              |400              |**2.1792**
6  |model000000500.model  |300              |300              |2.5610
7  |model000000500.model  |300              |400              |2.4019

It was werid.
**Do yo know why?**
IT 500, LR 0.000081, TEER/T1 85.72, TLOSS 0.529820, VEER 2.5610

The `scores.txt` was attached as below,
[scores-max_frames_300.txt](https://github.com/clovaai/voxceleb_trainer/files/5173320/scores-max_frames_300.txt)

As reference, I also attached my train under `--max_frames 200`
IT 500, LR 0.000081, TEER/T1 74.40, TLOSS 1.012739, VEER 2.4178
[scores-max_frames_200.txt](https://github.com/clovaai/voxceleb_trainer/files/5173322/scores-max_frames_200.txt)
