### ISSUE TITLE
Comparing to your previous paper(VoxCeleb2)

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#32]
In your previous VoxCeleb2 paper, the best EER on VoxCeleb1 is 2.87%, whose model applies NetVLAD/GhostVLAD. But here you apply SAP. Currently ignoring Angular Prototypical loss, you also get a good result (2.36) using CosFace/ArcFace, which is better than 2.87% too. What do you think the factor that leads to this better result? SAP or training for 500 epochs ?  The title of the paper is "In denfense of metric learning", I guess you want to assert more on the best result given by Angular Prototypical loss, but the thing is Cosface/ArcFace also achieves close result(2.36%).

**Comment by jlian2** [comment]
Plus, did you tried the model without using SAP?

**Comment by joonson** [comment]
Our updated [tech report](https://arxiv.org/abs/2009.14153) provides more analysis. We tried ASP as well here.
