### ISSUE TITLE
Angular Prototypical and # of classes

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#34]
Does it consider all classes(5994) in a mini-batch? I am confused of this because if a mini-batch size is only 800, then maximum number of classes is just 800?

**Comment by lbjcom** [comment]
> Does it consider all classes(5994) in a mini-batch? I am confused of this because if a mini-batch size is only 800, then maximum number of classes is just 800?

Yes, the number of output classes is same as the batch size in angular prototypical loss. But the output label is not used in the evaluation.
