### ISSUE TITLE
Pairwise for 10 features when evaluation

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#36]
May I know what is the intuition using pairwise distance of 10-features when doing evaluation instead of using cosine-similarity. I have tried cs, but performance is worse.

**Comment by joonson** [comment]
1. The test-time augmentation scheme is explained in Section 4.4 of https://arxiv.org/pdf/1806.05622.pdf .
2. See my comment in #4 for the relationship between cosine distance and Euclidean.
