### ISSUE TITLE
Questions about the test list

### ISSUE THREAD

**Issue by yy835055664** [clovaai/voxceleb_trainer#39]
Hello, I would like to ask a few questions about the test list
1. What does 1 or 0 in the first column of the test list mean?
2. There are two voice tags on each line in the test list. Do I have to set this up?
3. If I use my own data set, do I need to arrange it according to the training list and test list?

**Comment by joonson** [comment]
1. `1` means same speaker, `0` means different speakers
2. Yes, you need positive and negative pairs in the test set.
3. Yes, you will need to prepare the data in the same format.
