### ISSUE TITLE
Missing Details in README and code

### ISSUE THREAD

**Issue by 009deep** [clovaai/voxceleb_trainer#4]
1.  In paper you've mentioned,  

> For each epoch, we sample a maximum of 100 utterances from each of the 5,994 identities

In code that propagates as value of nSpeakers args parameter for angular prototypical. To derive result shared in paper what value of nSpeakers is used  for non softamx losses?

2. Both prototypical and angular prototypical, has hyperparmeter M. How to set that parameter in code ?(For other losses there is option to pass values m  and s in args).

3. This is related approach for evaluation and  does not require correction: You have used Euclidean norm for similarity.  Many earlier work on speaker verification including [voxceleb](http://www.robots.ox.ac.uk/~vgg/publications/2019/Nagrani19/nagrani19.pdf) used  cosine similarity. I evaluated result with cosine similarity and _EER_ comes to  _2.2693_ . Slightly higher but not  by large.  Any reason to use Euclidean norm  over cosine  similarity?

**Comment by joonson** [comment]
1. This line

> For each epoch, we sample a maximum of 100 utterances from each of the 5,994 identities

equates to `--max_seg_per_spk=100` in the code.

2. For metric learning losses, `--nSpeakers` argument should be the value of M. For best performance on the VoxCeleb1 test set, use `--nSpeakers=2`. These parameters are described inside `trainSpeakerNet.py`

3. If the embeddings are L2 normalized, the **squared** Euclidean distance is directly proportional to the cosine distance. The order of distances (and therefore EER) should remain the same no matter which of the two distance metrics is used.

<img width="318" alt="sqeuc" src="https://user-images.githubusercontent.com/9700334/79573939-5be2f000-80fa-11ea-9f2b-8f50953a2326.png">
