### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by yy835055664** [clovaai/voxceleb_trainer#40]
Hello, thank you very much for your extensive experiment. I have a question for you.
In the experimental results, both GE2E and Prototypical Angular Prototypical use M (2, 3, 4 5） for comparison test, how do you set this M in the code?

**Comment by joonson** [comment]
`M` in the paper is `nSpeakers` in the code for metric learning based loss functions

**Comment by yy835055664** [comment]
> M in the paper is nSpeakers in the code for metric learning based loss functions

Thank you very much, I still need to ask some questions.
1. When adjusting the M value, are other parameters (m, s) set to 0 or the default value in the code is selected? (Such as GE2E, Prototypical, Angular Prototypical)
2. In Triplet loss, does CHNM directly choose hard_prob=0.5,hard_rank=10?

**Comment by joonson** [comment]
1. The values of `m` and `s` don't matter for metric learning objectives.
2. No, curriculum hard negative mining is not implemented in this code. You will need to do this by stopping and re-starting the experiment with the new parameters.

**Comment by yy835055664** [comment]
> 1. The values of `m` and `s` don't matter for metric learning objectives.
> 2. No, curriculum hard negative mining is not implemented in this code. You will need to do this by stopping and re-starting the experiment with the new parameters.

thank you very much
