### ISSUE TITLE
how do I train angular-prototypical loss for M=2?

### ISSUE THREAD

**Issue by zeek-han** [clovaai/voxceleb_trainer#41]
I tried nSpeakers=2 to make gsize_dict['angleproto'] == 2, 
but lowest VEER is about 2.58% until the 400 Epoch with training batch size 400  (--nSpeakers=2, --batch_size=200)

how do I train angular-prototypical loss for M=2??
Thank you...

**Comment by joonson** [comment]
For best performance, try:

1. Larger batch size (e.g. --nSpeakers=2, --batch_size=400) 
2. Longer `max_frames` (e.g. 400 frames) during test phase

**Comment by zeek-han** [comment]
Thank you,
do I need extra setting for M=2?

**Comment by joonson** [comment]
No extra settings are required.

**Comment by zeek-han** [comment]
thank you so much.
