### ISSUE TITLE
Why using different input features

### ISSUE THREAD

**Issue by LeslieMei** [clovaai/voxceleb_trainer#47]
Hello, just want to enquire for why using different input features for different network (Mel Spectrogram for VGG, Spectrogram for ResNet)? And which is better?
I have tried to use Spectrogram in VGG, and in my experiment, there is not much difference regarding the final performance comparing to Mel Spectrogram.

**Comment by joonson** [comment]
In our experience the choice of input features doesn't make much difference to performance.
