### ISSUE TITLE
Regarding SAP  implemantaion

### ISSUE THREAD

**Issue by 009deep** [clovaai/voxceleb_trainer#48]
@joonson Would you provide, some reference (paper/github) using which SAP is implemented? I have hard time understanding what is being done.

One  such question is why non-linearity is used for this projection?
`torch.tanh(self.sap_linear(x))`

Also , does `[self.attention]` gets trained as part of training?

I made changes to convert it to multi-head vs single one as implemented here, even though code works and I can train model I am not seeing improvement. Having better understanding would help. Thanks.

**Comment by joonson** [comment]
We follow the implementation described in [this paper](https://arxiv.org/pdf/1804.05160.pdf). Equation 1 in this paper uses tanh non-linearity. 

`self.attention` is trained together with the network.
