### ISSUE TITLE
Fast ResNet-34?

### ISSUE THREAD

**Issue by LeslieMei** [clovaai/voxceleb_trainer#51]
Hi, I didn't find Fast ResNet-34 in the paper. After comparing it with the Thin ResNet-34 in the code, are the differences between them only the input features(Spectrogram for Thin ResNet-34, MelSpectrogram for Fast ResNet-34) and the lack of maxpool layer in Fast ResNet-34?

**Comment by gancx** [comment]
> Hi, I didn't find Fast ResNet-34 in the paper. After comparing it with the Thin ResNet-34 in the code, are the differences between them only the input features(Spectrogram for Thin ResNet-34, MelSpectrogram for Fast ResNet-34) and the lack of maxpool layer in Fast ResNet-34?

I wonder where you can the code of Thin ResNet34. i found the implementation is different from that in the original paper.
