### ISSUE TITLE
Is the thinResNet34 with angular-prototypical the state-of-the-art neural network you know?

### ISSUE THREAD

**Issue by zeek-han** [clovaai/voxceleb_trainer#54]
Thank you for this open source and your paper "In defence of metric learning for speaker recognition".

In this paper, your "proposed metric learning objective outperform state-of-the-art methods."
The best network in the paper is thin ResNet34 with angular-prototypical loss.
Is the best network you know?
Is there any update? 

If my question is not rude, please teach me which network is the best you know...
Thank you.

**Comment by joonson** [comment]
[This paper](https://ieeexplore.ieee.org/abstract/document/9053209/?casa_token=y2TvjYxHjXEAAAAA:FP2M-XJIqCvpJ8weYmAjQkTPcqDTfvmwDb3162I5O7LGHW8nUMQaR6Ap6Bb9O_X86jgeY2EFsQBuDg) has better results than ours, but also using a much larger network.
We have some minor updates (e.g. change of input dimensions, etc.) that makes small improvement to performance -- we will release this soon.

**Comment by zeek-han** [comment]
Thank you so much~

**Comment by zeek-han** [comment]
Thank you for your answer,  but this paper you mentioned above(Jhu-HLTCOE System for the Voxsrc Speaker Recognition Challenge)  was 2nd ranked in VOXSRC 2019. 
In Voxsrc2019, BUT system showed its superiority to Jhu-HLTCOE System, doesn't it?
BUT system was the winner of VOXSRC 2019.

I am confused with the State of the Art....please let me know....thank you...


BUT system:  https://arxiv.org/pdf/1910.12592.pdf

**Comment by joonson** [comment]
I know that there are several works that has lower EER than our baseline, but don't have an exhaustive list of them. For example, [this paper](https://www.isca-speech.org/archive/Interspeech_2019/pdfs/3146.pdf) **claims** an EER as low as 0.5% but we cannot validate the claim.

**Comment by zeek-han** [comment]
Thank you very much!!
the paper which claims to achieve EER 0.55% made me surprised!
Actually I cannot accept the claim even though the paper in on InterSpeech...but it was so impressive, thank you.
