### ISSUE TITLE
SEBasicBlock  operation order

### ISSUE THREAD

**Issue by cirograciapons** [clovaai/voxceleb_trainer#57]
Hello , assuming SEBasicBlock wants to be an extended BasicBlock from typical Resnet Implementation (torchvision)

i dont understand why the order of the operations is different here : https://github.com/clovaai/voxceleb_trainer/blob/master/models/ResNetBlocks.py#L25
In torchvision basic block relu goes after batch norm. is this a bug or there is a special reason for this change? 

thank you in advance

**Comment by joonson** [comment]
The order of BN and ReLU is always the subject of debate. I selected this order because it worked well on this task.
