### ISSUE TITLE
ResNetSE34 result question

### ISSUE THREAD

**Issue by yy835055664** [clovaai/voxceleb_trainer#58]
Hello, I am reproducing your code recently.
When running the ResNetSE34 model, Loss=nan, and an error is reported: ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
There is no such problem when running VGG and ResNetSE34L models.
How can this problem be solved?

**Comment by joonson** [comment]
I've never run into this issue. Anyone with experience?

**Comment by muzihuole** [comment]
> Hello, I am reproducing your code recently. When running the ResNetSE34 model, Loss=nan, and an error is reported: ValueError: Input contains NaN, infinity or a value too large for dtype('float64'). There is no such problem when running VGG and ResNetSE34L models. How can this problem be solved?

I also have this problem. Can you tell me how to solve it？

**Comment by hongyuwang414** [comment]
> > 您好，我最近正在复制您的代码。运行 ResNetSE34 模型时，Loss=nan，并报告错误：ValueError：输入包含 NaN、无穷大或对于 dtype（'float64'）来说太大的值。运行 VGG 和 ResNetSE34L 型号时没有这样的问题。如何解决这个问题？
> 
> 我也有这个问题。你能告诉我如何解决吗？

Have you solved this problem？
