### ISSUE TITLE
Add data augmentation

### ISSUE THREAD

**Issue by joonson** [clovaai/voxceleb_trainer#59]
- Online data augmentation (RIR and MUSAN noise)
- Should retain backward compatibility with existing models and loss functions

**Comment by ShaneRun** [comment]
@joonson 
Sounds good.
By the way, is there any tricks you will do to get earlier convergence instead of running for several hundreds of epoch?

**Comment by joonson** [comment]
@ShaneRun The reason that the `ResNetSE34L` takes so long to converge is because it has so few parameters. The very thin network takes much longer to converge. If you use the regular ResNet34 for example, it should converge to the same performance in less than 100 epochs.
