### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'finfo'

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#6]
Once I use "ResnetSE34L", it shows:
File "/home/user/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 23, in <module>
    EPSILON = torch.tensor(torch.finfo(torch.float).eps, dtype=torch.get_default_dtype())
AttributeError: module 'torch' has no attribute 'finfo'

**Comment by joonson** [comment]
I cannot reproduce this error. Can anyone else?
