### ISSUE TITLE
Add distributed training

### ISSUE THREAD

**Issue by joonson** [clovaai/voxceleb_trainer#61]
- Multi-GPU training using `DistributedDataParallel` (single node for now)
  - Pytorch `DataParallel` is no longer recommended

**Comment by wuqiangch** [comment]
@joonson Have added it to the code? I can't find it.Thanks!

**Comment by joonson** [comment]
Not yet, hence the open issue

**Comment by joonson** [comment]
Added in a new branch `distributed`.

**Comment by 009deep** [comment]
@joonson  8 different gpus or 8 cores on a single gpu?

**Comment by 009deep** [comment]
Also in [this comment](https://github.com/clovaai/voxceleb_trainer/issues/62#issuecomment-696470701) there  is separate config  vs one mentioned [above](https://github.com/clovaai/voxceleb_trainer/issues/61#issuecomment-698787004). Are both of them producing  same results?

**Comment by zeek-han** [comment]
Thank you always.
you said we must change the configuration when we use that code with different GPU environment.
Could you recommend configuration for 2 GPU?

**Comment by joonson** [comment]
@zeek-han The number of distributed GPU affects the training in the same way changing the batch size does. You will need to experiment to find out what works best.

**Comment by joonson** [comment]
@009deep Very similar, but not exactly the same.

**Comment by lawlict** [comment]
> Added in a new branch `distributed`. [This](https://github.com/clovaai/voxceleb_trainer/files/5281560/B2.yaml.txt) is the configuration used to produce `EER 1.1771` in the released pre-trained model. Note that 8 GPUs were used to train this model, so `test_interval` and `max_epoch` must be changed accordingly if you want to use a different number of GPUs.

Hi, @joonson. I test [This](https://github.com/clovaai/voxceleb_trainer/files/5281560/B2.yaml.txt) configuration but the EER is 2.4%. Note that it only trains for 36 epochs. Is that right?

**Comment by joonson** [comment]
@lawlict Did you train using distributed training with 8 GPUs?

**Comment by lawlict** [comment]
@joonson Yes, of course. I think the number of training steps is too small. 

> Also in [this comment](https://github.com/clovaai/voxceleb_trainer/issues/62#issuecomment-696470701) there is separate config vs one mentioned [above](https://github.com/clovaai/voxceleb_trainer/issues/61#issuecomment-698787004). Are both of them producing same results?

Another configuration here takes much more training steps, but I don't have time to test it now.
