### ISSUE TITLE
Training details for the new best model

### ISSUE THREAD

**Issue by hwidong-na** [clovaai/voxceleb_trainer#62]
Hi,

Thank you for your effort to provide improved baseline model.
It would be helpful for me to know more information e.g. hyperparameters for training the model.

Best,
Hwidong

**Comment by joonson** [comment]
[This](https://github.com/clovaai/voxceleb_trainer/files/5258878/B2SF.txt) is the configuration used, but it would take over 10 days to train on a single V100 GPU. We trained this using distributed training which is currently undergoing some testing before the public release (#61).

**Comment by joonson** [comment]
See #61
