### ISSUE TITLE
About the data augment

### ISSUE THREAD

**Issue by wuqiangch** [clovaai/voxceleb_trainer#63]
@joonson  In rirs_noises,the files almost   are multi-channel.So,Did you first convert files with multi-channel to single-channel? 
Because the function convolve in signal gets the two arrays which  should have the same number of dimensions . If I dont do that ,I will get the error "ValueError: volume and kernel should have the same dimensionality" in code "signal.convolve(audio, rir, mode='full')[:,:self.max_audio]".

**Comment by joonson** [comment]
Can you give me the name of the file that is multi-channel? They look like single channel to me.

**Comment by wuqiangch** [comment]
@joonson ‘RIRS_NOISES/real_rirs_isotropic_noises/RWCP_type1_rir_circle_e1c_imp040.wav’

**Comment by joonson** [comment]
Did you extract the files using `./dataprep.py`? This file should not be included.

**Comment by wuqiangch** [comment]
Oh， I'am sorry. I only download it. Thanks! It works.
