### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by dendi123** [clovaai/voxceleb_trainer#65]
Hello,
Im trying to train VGGVox model but sometimes I got this error
`OSError: [Errno 5] Input/output error
`
This is pretty annoying because sometimes it leads to this 'ZeroDivisionError: division by zero' which stop my trainning.
1. Are there anyway can I fix this problem
2. How can I save the process if problems occured ( crashing, power cutting )
I have been trainning for 1 day and this happened :(
And Im using the config ( on readme files ) for trainning VGGVox, does this affect the result much?

Thanks you very much,
I Hope you have a nice day,

**Comment by joonson** [comment]
I have never heard of this problem before. What is your operating system and GPU?

**Comment by dendi123** [comment]
I solved this problem. Im currently running a dual boot ( Windows / Ubuntu ). I put the dataset in Windows partition so the files might be missing or this problem may occurs. 
Thanks for sharing this project
