### ISSUE TITLE
Training speed difference between hdd and ssd

### ISSUE THREAD

**Issue by gustmd0121** [clovaai/voxceleb_trainer#67]
Hello 
Is there a big difference in training time between hdd and ssd? 
I use hdd and get around 500 hz but it fluctuates quite often to lower hz. I was wondering if anyone had comparable experience between the two. Thank you.

**Comment by joonson** [comment]
This can be a symptom of slow random access in some hard drive. We recommend using SSDs, but it may help to use more data loader threads if that's not possible.
