### ISSUE TITLE
In eval phase, is it correct to use L2 distance even for Angular xx losses?

### ISSUE THREAD

**Issue by w4-jonghoon** [clovaai/voxceleb_trainer#68]
https://github.com/clovaai/voxceleb_trainer/blob/6d3db45cbe00c27df71d6b04ca5fec0edc5317ac/SpeakerNet.py#L158

While training, you used cosine similarity as a distance metric for several loss objects, but in the evaluation, it seems you only used L2 distance (https://pytorch.org/cppdocs/api/function_namespacetorch_1_1nn_1_1functional_1a902d9a614b0a9e7a1073212da99ec5da.html)
I think this may occur wrong calculation.
Could you please review this problem?

**Comment by joonson** [comment]
See my comment to #4

**Comment by w4-jonghoon** [comment]
Thank you @joonson !
