### ISSUE TITLE
ResnetSE34 and I got an EER of 39

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#7]
I use the pretrained model and just apply "ResnetSE34", I got an EER of 39?

**Comment by joonson** [comment]
The pretrained model is for `ResNetSE34L`. If you need the model for `ResNetSE34`, then use [ this model](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/models/baseline_ap.model).

**Comment by jlian2** [comment]
> The pretrained model is for `ResNetSE34L`. If you need the model for `ResNetSE34`, then use [ this model](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/models/baseline_ap.model).

Thanks!
