### ISSUE TITLE
cleaned trial pairs of vox1

### ISSUE THREAD

**Issue by Shane-pe** [clovaai/voxceleb_trainer#73]
@joonson 
There are several trial pairs of VoxCeleb1, what is the difference between original and `cleaned` version?

>List of trial pairs - VoxCeleb1
List of trial pairs - VoxCeleb1 (cleaned)
List of trial pairs - VoxCeleb1-H
List of trial pairs - VoxCeleb1-H (cleaned)
List of trial pairs - VoxCeleb1-E
List of trial pairs - VoxCeleb1-E (cleaned)

**Comment by joonson** [comment]
The videos are manually checked and the mislabelled files are moved.

**Comment by Shane-pe** [comment]
@joonson 
Thanks, Mr. Chung!
You are always nice, patient and helpful.
