### ISSUE TITLE
Assertion Error when trainning VGGVox

### ISSUE THREAD

**Issue by huyvl** [clovaai/voxceleb_trainer#75]
Hello @joonson @dvisockas 
I'm currently trying to train VGGVox with different max_epoch. I successfully run it for 3 times. But this time I got this error. I used default arguments.
```
Traceback (most recent call last):
  File "trainSpeakerNet.py", line 161, in <module>
    loss, traineer = s.train_network(loader=trainLoader);
  File "/home/huyle/VGGVox/SpeakerNet.py", line 63, in train_network
    nloss, prec1 = self.__L__.forward(feat,label)
  File "/home/huyle/VGGVox/loss/amsoftmax.py", line 29, in forward
    assert x.size()[1] == self.in_feats
```
The Last Time, I got this , it was run on PyCharm but I ignored it and run on my terminal instead. And now it happens again on both PyCharm and Terminal. I tried to throw it but I'm afraid this will some how affect the results. Thanks you guys very much.

**Comment by zabir-nabil** [comment]
@huyvl how did you fix this issue? I'm facing the same error with RawNet.
