### ISSUE TITLE
train_list not found

### ISSUE THREAD

**Issue by rohitpaturi** [clovaai/voxceleb_trainer#77]
Hi, First of all, thanks for the amazing work and for sharing with us.
I am trying to reproduce the train run as mentioned in the README:
python ./trainSpeakerNet.py --model ResNetSE34L --trainfunc angleproto --batch_size 400 --nPerSpeaker 2 --train_list train_list.txt --test_list test_list.txt 

But, I am unable to find the train_list and test_list (dataprep.py just downloads, converts the data to wav). How do I generate the lists (with data augmentation) to replicate the model with 2.17 EER? Thanks

**Comment by alikhabazian** [comment]
how did you skip this problem?
