### ISSUE TITLE
THIS ISSUE WAS DELETED AND BLOCKED

### ISSUE THREAD

**Issue by vuongvantinh** [clovaai/voxceleb_trainer#79]

**Comment by joonson** [comment]
You need to set a threshold (e.g. -1), above which is 1 and below is 0.

**Comment by joonson** [comment]
No, there is no standard threshold. You will need to find a threshold that works best for your application.

**Comment by vuongvantinh** [comment]
Is there any way to find the best threshold to get high accuracy (not EER)? I just set the threshold manually.

**Comment by joonson** [comment]
You should save the scores to file and iterate over all thresholds.
