### ISSUE TITLE
Question about contrastive loss input

### ISSUE THREAD

**Issue by jlian2** [clovaai/voxceleb_trainer#8]
`for findex, key in enumerate(dictkeys):
            data    = self.data_dict[key]
            numSeg  = round_down(min(len(data),self.max_seg_per_spk),self.gSize) 
            
            rp      = lol(numpy.random.permutation(len(data))[:numSeg],self.gSize)
            
            flattened_label.extend([findex] * (len(rp)))
            for indices in rp:
                flattened_list.append([data[i] for i in indices])`
It seems that all of input pairs are from the same person e.g (p1,p1),(p2,p2),(p3,p3). Is there an input pair containing utterances from different person such as (p1,p2)? Thanks!

**Comment by joonson** [comment]
Negative pairs are generated here during the forward pass.

https://github.com/clovaai/voxceleb_trainer/blob/c43bceddd6982d3c4d6bad472932627502d619b3/loss/pairwise.py#L31-L33

**Comment by jlian2** [comment]
> Negative pairs are generated here during the forward pass.
> 
> https://github.com/clovaai/voxceleb_trainer/blob/c43bceddd6982d3c4d6bad472932627502d619b3/loss/pairwise.py#L31-L33
Thanks!
