### ISSUE TITLE
Problems with VGGVox's result

### ISSUE THREAD

**Issue by huyvl** [clovaai/voxceleb_trainer#82]
Hello @joonson  @dvisockas I have trained with the VGG40 network, the results and setting of hyper parameters are in scores.txt.
BUt the results are kinda weird
[scores.txt](https://github.com/clovaai/voxceleb_trainer/files/5585016/scores.txt)
Do you think the results are normal ?

**Comment by joonson** [comment]
I think it makes sense for VGGVox. What do you think is weird about it?

**Comment by huyvl** [comment]
> I think it makes sense for VGGVox. What do you think is weird about it?

Hi thanks for replying,I dont know why the TEER is only about 20%, should it nearly 80%?

**Comment by muzihuole** [comment]
Could you provide me the pretrained model of VGGVox? Looking forward to your reply.

**Comment by Jungjee** [comment]
Closing this issue as it has been inactive.
For the VGGVox model, the scores seems to be fine.
