### ISSUE TITLE
Question about reading wav

### ISSUE THREAD

**Issue by whitegon** [clovaai/voxceleb_trainer#85]
I am adding VAD in the preprocessing about wav file, and I find there is a difference between wavfile.read and torchaudio.load.
Why you use scipy.io not torchaudio?

**Comment by whitegon** [comment]
I find there is no difference in the training result.
But, the VAD which is implemented by torchaudio is a little bit slow.
Each wav file needs about 500~800ms to compute VAD.
Does anyone has used the other VAD implementation?

**Comment by Naminwang** [comment]
Face the same problem，have you found the replacement vad method?

**Comment by whitegon** [comment]
> Face the same problem，have you found the replacement vad method?

I use the webrtcvad to preprocess the file before I start to train.

**Comment by JJ-Guo1996** [comment]
> I find there is no difference in the training result. But, the VAD which is implemented by torchaudio is a little bit slow. Each wav file needs about 500~800ms to compute VAD. Does anyone has used the other VAD implementation?

Hi, how about the performance after using the VAD?
