### ISSUE TITLE
Regarding ECAPA-TDNN implementation

### ISSUE THREAD

**Issue by 009deep** [clovaai/voxceleb_trainer#86]
Hi @joonson, In you your voxsrc 20 summary [paper](https://arxiv.org/pdf/2010.15809.pdf), you have mentioned you implemented ECAPA-TDNN  network with help of Brecht. 
Could you provide that network implementation details? It's hard to understand from paper.

**Comment by joonson** [comment]
Hi, here is our implementation of the network. Let me know if it works -- I might merge this into the repository in a future update.

[ECAPA.zip](https://github.com/clovaai/voxceleb_trainer/files/5653564/ECAPA.zip)

**Comment by 009deep** [comment]
thank  you so much.

**Comment by lawlict** [comment]
Hi, @joonson. I find that the ECAPA_TDNN model runs slow. When I set the bias of Conv1d in Line 46 to `False`, it works normally: 
```
for i in range(self.nums):
    convs.append(nn.Conv1d(width, width, kernel_size=kernel_size, dilation=dilation, padding=num_pad, bias=False))
    bns.append(nn.BatchNorm1d(width))
```
Do you meet the same problem? I'm just confused by the phenomenon.

**Comment by Reptilefury** [comment]
is there an implementation using Tensorflow

**Comment by Jungjee** [comment]
Hi @Reptilefury, at this moment, we are not considering the support of Tensorflow in this repository.
