### ISSUE TITLE
question about data transpose in SpeakerNet.py

### ISSUE THREAD

**Issue by forwiat** [clovaai/voxceleb_trainer#92]
Hi @joonson , Thank you so much for the great work you shared.
I am confused that why do "transpose(1, 0)" before feedward model in training. `data    = data.transpose(1,0).` This code is in line95 SpeakerNet.py. Does it means transpose batch and frames?

**Comment by joonson** [comment]
Its basically transposing `N` and `M` in the paper, not frames.
