### ISSUE TITLE
Question about converting to TensorFlow

### ISSUE THREAD

**Issue by navid-a** [clovaai/voxceleb_trainer#95]
First of all, thank you for your great contributions! I'm a fan of this and your previous work with NetVlad layers.

I am working on a project in Tensorflow, and I have been trying to convert this pytorch model to TF (using pytorch2keras). I have not been successful yet, mostly because it seems that this code needs a GPU configured to define the model (and my cuda is not correctly configured for pytorch.)

I was wondering if you happen to have a Tensorflow implementation? If not, is there an easy way of running this code only on cpu? I don't need to run training, only model creation and inference.

**Comment by Jungjee** [comment]
Thank you for the interest. 
We currently do not have plans for Tensorflow support in the meanwhile.
