### ISSUE TITLE
About the changing training data sample rate

### ISSUE THREAD

**Issue by whitegon** [clovaai/voxceleb_trainer#97]
If I want to use 8k NIST SRE data to train my system.
Do I need to change the setting about n_fft, win_length, and hop_length in 
torchaudio.transforms.MelSpectrogram(sample_rate=8000, n_fft=512, win_length=400, hop_length=160, window_fn=torch.hamming_window, n_mels=n_mels) ?

**Comment by joonson** [comment]
It would be best to up-sample the input to 16kHz using ffmpeg prior to training.

**Comment by ukemamaster** [comment]
@joonson Why is it recommended to up-sample to 16kHz? Why can't we down-sample to 8kHz? Will it degrade the performance?
